databases:
  # PostgreSQL database
  - name: vheer-db
    databaseName: vheer_production
    user: vheer_admin
    plan: free
    region: oregon
    postgresMajorVersion: 15

services:
  # Backend service
  - type: web
    name: vheer-api
    runtime: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vheer-db
          property: connectionString
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      # API Keys are managed in Render Dashboard for security
      # The following keys must be set in Environment Groups or Service Environment:
      # - FLUX_API_KEY
      # - FLUX_API_URL
      # - GPT_IMAGE_API_KEY
      # - GPTIMAGE_API_URL
      # - IMGBB_API_KEY
      # - MIDJOURNEY_API_KEY (optional)
      # - MIDJOURNEY_API_URL (optional)
      - key: CORS_ORIGIN
        value: https://colibrrri.com
      - key: BASE_URL
        value: https://colibrrri.com
      - key: FRONTEND_URL
        value: https://colibrrri.com
      - key: GOOGLE_CLIENT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend service
  - type: static
    name: vheer-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://vheer-api.onrender.com https://api.openai.com https://api.anthropic.com; default-src 'self' https://vheer-client.onrender.com"
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://colibrrri.com/api
      - key: NODE_ENV
        value: production
      # Frontend API keys are managed in Render Dashboard
      # Set these in Service Environment:
      # - VITE_FAL_API_KEY
      # - VITE_FLUX_API_KEY
    autoDeploy: true